project:
  type: website
  output-dir: docs

website:
  title: "reports"
  navbar:
    left:
      - href: work/computeTopo.Rmd
        text: "Exposition Topographique"
      - text: "Travaux en cours"
        menu: 
          - href: work/openeo.Rmd
            text: "Récupérer données"
      - href: about.qmd
        text: "A propos"
  sidebar:
    style: "docked"
    search: true 
    contents:
      - section: "Rapports Hebdomadaires"
        contents:
          - section: "Janvier" 
            contents:
              - href: hebdos/hebdo_1.Rmd
                text: "Semaine 1"
              - href: hebdos/hebdo_2.Rmd
                text: "Semaine 2"
              - href: hebdos/hebdo_3.Rmd
                text: "Semaine 3"
          - section: "Février" 
            contents:
              - href: hebdos/hebdo_4.Rmd
                text: "Semaine 4"
              - href: hebdos/hebdo_5.Rmd
                text: "Semaine 5"
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

